repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
    - id: check-ast
      language_version: python3.8
    - id: check-merge-conflict
    - id: check-json
    - id: check-yaml

-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.1
    hooks:
      -   id: python-safety-dependencies-check

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
    - id: flake8
      # args: ['--config=.flake8']
      language_version: python3.8

- repo: https://github.com/ambv/black
  rev: 20.8b1
  hooks:
    - id: black
      language_version: python3.8
      files: ^app/.*\.py$


- repo: https://github.com/PyCQA/bandit
  rev: 1.6.2
  hooks:
    - id: bandit
      args: [-l, --recursive, -x, tests]
      files: ^app/.*\.py$

- repo: local
  hooks:
    - id: unit-tests
      name: Unit Tests
      entry: sh -c "echo 'Here I will add my unit tests... IF I HAD ANY!' && exit 0"
      pass_filenames: false
      language: system
    - id: bdd-tests
      name: Behave Tests
      entry: sh -c "docker-compose build && docker-compose run seis_ee behave --tags=-skip"
      language: system
      pass_filenames: false
