version: "3.4"
services:
  decimator:
    image: ghcr.io/equinor/ccs-passive
    build: .
    ports:
      - "80:5000"
    environment:
      FILES_CONN_STRING: ${FILES_CONN_STRING}
      BLOB_CONN_STRING: ${BLOB_CONN_STRING}
      QUEUE_CONN_STRING: ${QUEUE_CONN_STRING}
      ENVIRONMENT: ${ENVIRONMENT}
      RUN_MODE: decimator
    volumes:
      - ./data:/app/data
    depends_on:
      - storage-emulator

  converter:
    image: ghcr.io/equinor/ccs-passive
    build: .
    environment:
      FILES_CONN_STRING: ${FILES_CONN_STRING}
      BLOB_CONN_STRING: ${BLOB_CONN_STRING}
      QUEUE_CONN_STRING: ${QUEUE_CONN_STRING}
      ENVIRONMENT: ${ENVIRONMENT}
      RUN_MODE: converter
    volumes:
      - ./data:/app/data
    depends_on:
      - storage-emulator
