version: "3.4"
services:
  seis_ee:
    image: seis-ee
#    entrypoint: bash
    build: .
    volumes:
      - ./data:/data
#       Update this line with your raw data location
      - ./test_data/OsebergC-SWIM_01:/raw/oseberg/OsebergC-SWIM_01
      - ./test_data/oseberg_sensors.csv:/raw/oseberg_sensors.csv

    command: stream-files