version: "3.4"
services:
  seis_ee:
    image: seis-ee
    build: .
    ports:
      - "80:5000"
    environment:
      FILES_CONN_STRING: ${FILES_CONN_STRING}
    volumes:
      - ./data:/app/data
    command: python3 /app/event_listener.py
