version: "3.4"
services:
  seis_ee:
    image: seis-ee
#    entrypoint: bash
    build: .
    volumes:
      - .:/data
#       Update this line with your raw data location
#      - ./test_data/:/raw
      - /project/grane-passive:/raw