version: "3.4"
services:
  seis_ee:
    image: seis-ee
#    entrypoint: bash
    build: .
    volumes:
      - ./data:/data
#       Update this line with your raw data location
      - ./test_data/oseberg:/raw/oseberg/oseberg
      - ./test_data/oseberg_sensors.csv:/raw/oseberg_sensors.csv
      - ./ssh:/home/seis/.ssh

    entrypoint: python3 /app/seis_ee.py