name: Build & publish container image
on:
  push:
    branches: [fix-docker-image-access]
jobs:
  build_and_push:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker login
        run: echo ${{ secrets.PRIVATE_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Pull latest
        run: docker pull ghcr.io/equinor/ccs-passive
      - name: get access to decimate image
        run: echo ${{ secrets.GITLAB_ACCESS_TOKEN }} | docker login registry.git.equinor.com/sentry/decimate -u ${{ secrets.GITLAB_USERNAME }} --password-stdin
      - name: Build
        run: docker build . --tag ghcr.io/equinor/ccs-passive --cache-from ghcr.io/equinor/ccs-passive
      - name: Push
        run: docker push ghcr.io/equinor/ccs-passive
