name: Build & publish container image
on:
  push:
    branches: [master]
jobs:
  build_and_push:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker login
        run: echo ${{ secrets.GH_REGISTRY }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Pull latest
        run: docker pull ghcr.io/equinor/css-passive
      - name: Build
        run: docker build . --tag ghcr.io/equinor/css-passive --cache-from ghcr.io/equinor/css-passive
      - name: Push
        run: docker push ghcr.io/equinor/css-passive
