name: Testing

on: [push]

jobs:
  testing:
    name: Run tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'
      - name: "pip install pre-commit and poetry"
        run: pip install pre-commit poetry
      - name: Pre-Commit
        # Until we can build the container (Open Source Decimate), use alternative config file.
        run: pre-commit run --all-files --verbose -c .pre-commit-config-ci.yaml
